
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://codeitsimple.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-86673704-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Alexandre Lafrance-Drouin"
title: "{ Code It Simple }"
description: "Personal blog of Alexandre Lafrance-Drouin. Opinions expressed are mine."
keywords: "Alexandre Lafrance-Drouin, technology, software engineering"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "fa-terminal"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "If you can dream it, you can do it."
  - text: "It always seems impossible until it's done."

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/Icon-ldpi.png"
icon-48p: "/img/web-app/Icon-mdpi.png"
icon-72p: "/img/web-app/Icon-hdpi.png"
icon-96p: "/img/web-app/Icon-xhdpi.png"
icon-144p: "/img/web-app/Icon-xxhdpi.png"
icon-192p: "/img/web-app/Icon-xxxhdpi.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "codeitsimple"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/intact.png"
    date: "September 2014 - Today"
    description: "Building amazing solution at Intact Financial Corp"
  - image: "/img/timeline/ultima.png"
    date: "September 2013 - September 2014"
    description: "Customer, meet broker, broker meet Insurers! Let's be friends!"
  - image: "/img/timeline/protectron.jpg"
    date: "September 2010 - September 2013"
    description: "Are you safe? Let's make sure we process all the signals! By the way, your door is not closed properly!"
  - image: "/img/timeline/roy.png"
    date: "September 2004 - September 2011"
    description: "You need a ninja? I'll be that ninja, from networking to programming, I've done it all here!"
# First image of the Timeline

timeline-img: "/img/author.png"

###########
# Contact #
###########

email: "aldrouin@codeitsimple.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Alexandre Lafrance-Drouin has been in the industry since 2007, working on different enterprise project. Based in Montréal, he spends most of his free time with his family, or keeps busy with programming, networking, building docker instances and thinkering with everything that relates to technology."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

img-404: "/img/labtocat.jpg"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false