---
title: "{ Code It Simple }"
timezone: "America/Montreal"
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://codeitsimple.com
baseurl: ''
google-tracking-id: UA-86673704-1
force-https: true
lang: en
author: Alexandre Lafrance-Drouin
description: Personal blog of Alexandre Lafrance-Drouin. Opinions expressed are mine.
keywords: Alexandre Lafrance-Drouin, technology, software engineering
favicon: "/img/favicon.ico"
black-favicon: fa-terminal
background-img: "../img/intro-bg.jpg"
dynamic-typing: true
shuffle: true
loop: true
loop-count: false
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
- text: If you can dream it, you can do it.
- text: It always seems impossible until it's done.
me-img: "/img/author.png"
color-browser: "#000000"
apple-status-bar-style: black
web-app-mode: true
icon-36p: "/img/web-app/Icon-ldpi.png"
icon-48p: "/img/web-app/Icon-mdpi.png"
icon-72p: "/img/web-app/Icon-hdpi.png"
icon-96p: "/img/web-app/Icon-xhdpi.png"
icon-144p: "/img/web-app/Icon-xxhdpi.png"
icon-192p: "/img/web-app/Icon-xxxhdpi.png"
enable-gesture-navigation: true
post-preview-words: 96
paginate: 5
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
google-plus-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true
disqus-shortname: codeitsimple
syntax-highlight: true
events:
- image: "/img/timeline/intact.png"
  date: September 2014 - Today
  description: Building amazing solution at Intact Financial Corp
- image: "/img/timeline/ultima.png"
  date: September 2013 - September 2014
  description: Customer, meet broker, broker meet Insurers! Let's be friends!
- image: "/img/timeline/protectron.jpg"
  date: September 2010 - September 2013
  description: Are you safe? Let's make sure we process all the signals! By the way,
    your door is not closed properly!
- image: "/img/timeline/roy.png"
  date: September 2004 - September 2011
  description: You need a ninja? I'll be that ninja, from networking to programming,
    I've done it all here!
timeline-img: "/img/author.png"
email: aldrouin@codeitsimple.com
author_blurb: Alexandre Lafrance-Drouin has been in the industry since 2007, working
  on different enterprise project. Based in Montréal, he spends most of his free time
  with his family, or keeps busy with programming, networking, building docker instances
  and thinkering with everything that relates to technology.
author_blurb_image: "/img/author.png"
social:
- title: twitter
  url: https://twitter.com/codeitsimple
- title: github
  url: https://github.com/aldrouin
- title: rss
  url: "/feed.xml"
img-404: "/img/labtocat.jpg"
pages_list:
  About: about
  Blog: latest-post
  Timeline: timeline
  Contact: contact
exclude:
- LICENSE
- README.md
- CONTRIBUTING
- CONTRIBUTORS
- scripts
paginate_path: blog/page:num/
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-github-metadata
- jekyll-relative-links
- jekyll-titles-from-headings
- jekyll-gist
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
