group :jekyll_plugins do
#    gem "jekyll-paginate", "1.1.0"
    gem "github-pages", "204"
#    gem "html-pipeline", "2.12.3"
#    gem "jekyll-avatar", "0.7.0"
#    gem "jekyll-default-layout", "0.1.4"
#    gem "jekyll-feed", "0.13.0"
#    gem "jekyll-gist", "1.5.0"
#    gem "jekyll-github-metadata", "2.13.0"
#    gem "jekyll-mentions", "1.5.1"
#    gem "jekyll-optional-front-matter", "0.3.2"
#    gem "jekyll-readme-index", "0.3.0"
#    gem "jekyll-redirect-from", "0.15.0"
#    gem "jekyll-relative-links", "0.6.1"
#    gem "jekyll-seo-tag", "2.6.1"
#    gem "jekyll-sitemap", "1.4.0"
#    gem "kekyll=titles-from-headings", "0.5.3"
#    gem "jemoji", "0.11.1"
#    gem "kramdown", "1.17.0"
#    gem "liquid", "4.0.3"
end

